/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Arko Sarkar' at '2/23/17 7:26 PM' with Gradle 2.14.1
 *
 * @author Arko Sarkar, @date 2/23/17 7:26 PM
 */

public class Library {
    public boolean hello(String value) {
		System.out.println("hello from library");
		return true;
    }
	
	public static void main(String args[]){
		System.out.println("Hello");
	}
}
