import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Arko Sarkar' at '2/23/17 7:26 PM' with Gradle 2.14.1
 *
 * @author Arko Sarkar, @date 2/23/17 7:26 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.hello(""));
		
    }
}
