/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Arko Sarkar' at '2/23/17 7:26 PM' with Gradle 2.14.1
 *
 * @author Arko Sarkar, @date 2/23/17 7:26 PM
 */
package com;
import org.apache.commons.lang.StringUtils;
public class MyStringUtils {
   public static boolean isEmpty(String value){
	   return StringUtils.isEmpty(value);
   }
}
